--if SC2 then
function CRITHIT()
  --game:GetService("ReplicatedStorage").WaitForChild("Packages").WaitForChild("Knit").WaitForChild("Services").WaitForChild("ArmWrestleService").WaitForChild("RF").WaitForChild("RequestEndFight"):InvokeServer()
  local remoteEvent = game:GetService("ReplicatedStorage"):WaitForChild("Packages"):WaitForChild("Knit"):WaitForChild("Services"):WaitForChild("ArmWrestleService"):WaitForChild("RF"):WaitForChild("RequestCritHit")
  if remoteEvent then
    remoteEvent:InvokeServer()
    remoteEvent:InvokeServer()
    remoteEvent:InvokeServer()
    remoteEvent:InvokeServer()
    remoteEvent:InvokeServer()
    remoteEvent:InvokeServer()
    remoteEvent:InvokeServer()
    remoteEvent:InvokeServer()
    remoteEvent:InvokeServer()
    remoteEvent:InvokeServer()
    remoteEvent:InvokeServer()
    remoteEvent:InvokeServer()
    remoteEvent:InvokeServer()
    remoteEvent:InvokeServer()
    remoteEvent:InvokeServer()
    remoteEvent:InvokeServer()
    remoteEvent:InvokeServer()
    remoteEvent:InvokeServer()
    remoteEvent:InvokeServer()
    remoteEvent:InvokeServer()
    remoteEvent:InvokeServer()
    remoteEvent:InvokeServer()
    remoteEvent:InvokeServer()
    remoteEvent:InvokeServer()
    remoteEvent:InvokeServer()
    -- Memanggil RemoteEvent
  else
    print("RemoteEvent tidak ditemukan!")
  end
end

--game:GetService("ReplicatedStorage"):WaitForChild("Packages"):WaitForChild("Knit"):WaitForChild("Services"):WaitForChild("ArmWrestleService"):WaitForChild("RF"):WaitForChild("RequestCritHit"):InvokeServer()
--game:GetService("ReplicatedStorage"):WaitForChild("Packages"):WaitForChild("Knit"):WaitForChild("Services"):WaitForChild("ArmWrestleService"):WaitForChild("RF"):WaitForChild("RequestCritHit"):InvokeServer()
--game:GetService("ReplicatedStorage"):WaitForChild("Packages"):WaitForChild("Knit"):WaitForChild("Services"):WaitForChild("ArmWrestleService"):WaitForChild("RF"):WaitForChild("RequestCritHit"):InvokeServer()
--game:GetService("ReplicatedStorage"):WaitForChild("Packages"):WaitForChild("Knit"):WaitForChild("Services"):WaitForChild("ArmWrestleService"):WaitForChild("RF"):WaitForChild("RequestCritHit"):InvokeServer()
--game:GetService("ReplicatedStorage"):WaitForChild("Packages"):WaitForChild("Knit"):WaitForChild("Services"):WaitForChild("ArmWrestleService"):WaitForChild("RF"):WaitForChild("RequestCritHit"):InvokeServer()
--game:GetService("ReplicatedStorage"):WaitForChild("Packages"):WaitForChild("Knit"):WaitForChild("Services"):WaitForChild("ArmWrestleService"):WaitForChild("RF"):WaitForChild("RequestCritHit"):InvokeServer()
--game:GetService("ReplicatedStorage"):WaitForChild("Packages"):WaitForChild("Knit"):WaitForChild("Services"):WaitForChild("ArmWrestleService"):WaitForChild("RF"):WaitForChild("RequestCritHit"):InvokeServer()
--game:GetService("ReplicatedStorage"):WaitForChild("Packages"):WaitForChild("Knit"):WaitForChild("Services"):WaitForChild("ArmWrestleService"):WaitForChild("RF"):WaitForChild("RequestCritHit"):InvokeServer()
--game:GetService("ReplicatedStorage"):WaitForChild("Packages"):WaitForChild("Knit"):WaitForChild("Services"):WaitForChild("ArmWrestleService"):WaitForChild("RF"):WaitForChild("RequestCritHit"):InvokeServer()
--game:GetService("ReplicatedStorage"):WaitForChild("Packages"):WaitForChild("Knit"):WaitForChild("Services"):WaitForChild("ArmWrestleService"):WaitForChild("RF"):WaitForChild("RequestCritHit"):InvokeServer()
  --wait(.1)
